import React, { useState, useEffect } from 'react';

/**
 * Legal Disclaimer Component
 * Displays risk warnings and terms of use for the trading platform
 */
export function LegalDisclaimer({ darkMode }) {
  const [expanded, setExpanded] = useState(false);

  return (
    <footer className="mt-8 border-t border-[var(--border-color)] pt-6 pb-8">
      <div className="max-w-4xl mx-auto px-4">
        {/* Always visible warning */}
        <div className="flex items-center justify-center gap-2 text-sm text-muted mb-4">
          <svg className="w-4 h-4 text-yellow-500" fill="currentColor" viewBox="0 0 20 20">
            <path fillRule="evenodd" d="M8.257 3.099c.765-1.36 2.722-1.36 3.486 0l5.58 9.92c.75 1.334-.213 2.98-1.742 2.98H4.42c-1.53 0-2.493-1.646-1.743-2.98l5.58-9.92zM11 13a1 1 0 11-2 0 1 1 0 012 0zm-1-8a1 1 0 00-1 1v3a1 1 0 002 0V6a1 1 0 00-1-1z" clipRule="evenodd" />
          </svg>
          <span>
            <strong>Risk Warning:</strong> Trading involves significant risk. Only invest what you can afford to lose.
          </span>
        </div>

        {/* Expandable disclaimer */}
        <button
          onClick={() => setExpanded(!expanded)}
          className="text-xs text-muted hover:text-[var(--text-primary)] transition-colors flex items-center gap-1 mx-auto"
        >
          {expanded ? 'Hide' : 'View'} Legal Disclaimers
          <svg
            className={`w-3 h-3 transition-transform ${expanded ? 'rotate-180' : ''}`}
            fill="none"
            viewBox="0 0 24 24"
            stroke="currentColor"
          >
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 9l-7 7-7-7" />
          </svg>
        </button>

        {expanded && (
          <div className="mt-4 p-4 rounded-lg bg-[var(--bg-secondary)] text-xs text-muted space-y-3">
            <div>
              <h4 className="font-semibold text-[var(--text-primary)] mb-1">Risk Disclosure</h4>
              <p>
                Trading cryptocurrencies and other financial instruments involves substantial risk of loss and is not
                suitable for all investors. The high degree of leverage available can work against you as well as for
                you. Before deciding to trade, you should carefully consider your investment objectives, level of
                experience, and risk appetite. The possibility exists that you could sustain a loss of some or all of
                your initial investment.
              </p>
            </div>

            <div>
              <h4 className="font-semibold text-[var(--text-primary)] mb-1">No Financial Advice</h4>
              <p>
                JJ-Bot does not provide financial, investment, legal, or tax advice. All trading strategies and
                signals generated by this software are for informational purposes only and should not be construed
                as personalized investment advice. You should consult with a qualified financial advisor before
                making any investment decisions.
              </p>
            </div>

            <div>
              <h4 className="font-semibold text-[var(--text-primary)] mb-1">No Guarantees</h4>
              <p>
                Past performance is not indicative of future results. There is no guarantee that any trading strategy
                or algorithm will be profitable. The AI/ML models used by this software may produce errors or
                inaccurate predictions. You acknowledge that you are using this software at your own risk.
              </p>
            </div>

            <div>
              <h4 className="font-semibold text-[var(--text-primary)] mb-1">Software Disclaimer</h4>
              <p>
                This software is provided "as is" without warranty of any kind, express or implied. The developers
                and operators of JJ-Bot are not responsible for any losses, damages, or costs arising from the use
                of this software, including but not limited to trading losses, data loss, or system failures.
              </p>
            </div>

            <div>
              <h4 className="font-semibold text-[var(--text-primary)] mb-1">Regulatory Compliance</h4>
              <p>
                Users are responsible for ensuring their use of this software complies with all applicable laws and
                regulations in their jurisdiction. JJ-Bot is not registered as a securities broker-dealer, investment
                advisor, or commodity trading advisor with any regulatory authority.
              </p>
            </div>

            <div className="pt-2 border-t border-[var(--border-color)]">
              <p className="text-center">
                By using JJ-Bot, you acknowledge that you have read, understood, and agree to these disclaimers.
              </p>
            </div>
          </div>
        )}

        {/* Footer links */}
        <div className="mt-4 flex items-center justify-center gap-4 text-xs text-muted">
          <span>JJ Gorilla Trading Systems</span>
          <span className="w-1 h-1 rounded-full bg-[var(--border-color)]" />
          <span>{new Date().getFullYear()} All rights reserved</span>
        </div>
      </div>
    </footer>
  );
}

/**
 * First-time disclaimer modal
 * Shows on first visit and requires acceptance
 */
export function DisclaimerModal({ isOpen, onAccept, darkMode }) {
  if (!isOpen) return null;

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/70">
      <div
        className="w-full max-w-2xl rounded-xl shadow-2xl overflow-hidden"
        style={{ background: 'var(--bg-primary)' }}
      >
        {/* Header */}
        <div className="p-6 border-b border-[var(--border-color)]">
          <div className="flex items-center gap-3">
            <div className="w-12 h-12 rounded-xl bg-gradient-to-br from-yellow-500 to-orange-500 flex items-center justify-center">
              <svg className="w-7 h-7 text-white" fill="currentColor" viewBox="0 0 20 20">
                <path fillRule="evenodd" d="M8.257 3.099c.765-1.36 2.722-1.36 3.486 0l5.58 9.92c.75 1.334-.213 2.98-1.742 2.98H4.42c-1.53 0-2.493-1.646-1.743-2.98l5.58-9.92zM11 13a1 1 0 11-2 0 1 1 0 012 0zm-1-8a1 1 0 00-1 1v3a1 1 0 002 0V6a1 1 0 00-1-1z" clipRule="evenodd" />
              </svg>
            </div>
            <div>
              <h2 className="text-xl font-bold">Important Risk Disclosure</h2>
              <p className="text-sm text-muted">Please read carefully before proceeding</p>
            </div>
          </div>
        </div>

        {/* Content */}
        <div className="p-6 max-h-96 overflow-y-auto text-sm space-y-4">
          <div className="p-4 rounded-lg bg-yellow-500/10 border border-yellow-500/30">
            <p className="font-semibold text-yellow-400 mb-2">High Risk Investment Warning</p>
            <p className="text-muted">
              Trading cryptocurrencies and other financial instruments carries a high level of risk and may not be
              suitable for all investors. You could lose all or part of your investment. Never invest money you
              cannot afford to lose.
            </p>
          </div>

          <div>
            <h3 className="font-semibold mb-2">By using JJ-Bot, you acknowledge:</h3>
            <ul className="list-disc list-inside space-y-2 text-muted">
              <li>You understand that trading involves significant risk of financial loss</li>
              <li>You are solely responsible for all trading decisions and outcomes</li>
              <li>JJ-Bot provides tools and information, not financial advice</li>
              <li>Past performance does not guarantee future results</li>
              <li>AI/ML predictions are not always accurate and may result in losses</li>
              <li>You have read and agree to the terms of service and privacy policy</li>
              <li>You are of legal age in your jurisdiction to use this software</li>
              <li>You will comply with all applicable laws and regulations</li>
            </ul>
          </div>

          <div className="p-4 rounded-lg bg-red-500/10 border border-red-500/30">
            <p className="text-red-400">
              <strong>DO NOT</strong> use this software with funds you cannot afford to lose.
              Start with paper trading to understand how the system works before risking real money.
            </p>
          </div>
        </div>

        {/* Footer */}
        <div className="p-6 border-t border-[var(--border-color)] flex items-center justify-between">
          <p className="text-xs text-muted">
            You must accept these terms to continue
          </p>
          <button
            onClick={onAccept}
            className="btn btn-primary px-6 py-2"
          >
            I Understand and Accept
          </button>
        </div>
      </div>
    </div>
  );
}

export default LegalDisclaimer;
